furniture_Factory/furniture_Factory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('workshop.urls')),
    path('', include('order.urls')),
    path('admin/', admin.site.urls),
]

furniture_Factory/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    # Путь для списка цехов
    path('list_order', views.OrderListView.as_view(), name='list_order'),

    # Путь для карточки цеха
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='detail_order'),

    # Путь для создания нового цеха
    path('order/create/', views.OrderCreateView.as_view(), name='create_order'),

    # Путь для редактирования цеха
    path('order/<int:pk>/edit/', views.OrderUpdateView.as_view(), name='edit_order'),

    # Путь для удаления цеха
    path('order/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='delete_order')
]

furniture_Factory/workshop/urls.py
from django.urls import path
from . import views

app_name = 'workshop'

urlpatterns = [
    # Путь для списка цехов
    path('', views.WorkshopListView.as_view(), name='list_workshop'),

    # Путь для карточки цеха
    path('<int:pk>/', views.WorkshopDetailView.as_view(), name='detail_workshop'),

    # Путь для создания нового цеха
    path('workshop/create/', views.WorkshopCreateView.as_view(), name='create_workshop'),

    # Путь для редактирования цеха
    path('workshop/<int:pk>/edit/', views.WorkshopUpdateView.as_view(), name='edit_workshop'),

    # Путь для удаления цеха
    path('workshop/<int:pk>/delete/', views.WorkshopDeleteView.as_view(), name='delete_workshop'),

    # Путь для списка работников
    path('workerlist/', views.WorkerListView.as_view(), name='list_worker'),

    # Путь для редактирования работников
    path('worker/<int:pk>/edit/', views.WorkerUpdateView.as_view(), name='edit_worker'),

    # Путь для создания нового работника
    path('worker/create/', views.WorkerCreateView.as_view(), name='create_worker'),

    # Путь для удаления работника
    path('worker/<int:pk>/delete/', views.WorkerDeleteView.as_view(), name='delete_worker')
]

furniture_Factory/order/models.py
from django.db import models

from workshop.models import Workshop


STATUS_CHOICES = [
    ('in progress', 'в процессе'),
    ('completed', 'завершен'),
    ('cancelled', 'отменен'),
]

class Order(models.Model):
    orderNumber = models.PositiveIntegerField(
        verbose_name='Номер заказа',
        unique=True
    )
    startDate = models.DateField(verbose_name='Дата начала')
    endDate = models.DateField(verbose_name='Дата окончания')
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='working',
        verbose_name='Статус'
    )
    workshops = models.ForeignKey(
        Workshop,
        verbose_name='Цех',
        on_delete=models.CASCADE,
        related_name='orders'
    )
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f"Заказ #{self.orderNumber}"

furniture_Factory/workshop/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.conf import settings
from django.core.exceptions import ValidationError
import re

from django.dispatch import receiver


def validate_time_range(value):
    # Регулярное выражение для формата времени HH:MM-HH:MM
    time_pattern = r"^([01]?[0-9]|2[0-3]):([0-5][0-9])\-([01]?[0-9]|2[0-3]):([0-5][0-9])$"
    match = re.match(time_pattern, value)
    if not match:
        raise ValidationError("Неверный формат времени. Используйте формат HH:MM-HH:MM.")

    # Проверка, что время начала не позже времени окончания
    start_time = value.split('-')[0]
    end_time = value.split('-')[1]

    start_hour, start_minute = map(int, start_time.split(':'))
    end_hour, end_minute = map(int, end_time.split(':'))

    if (start_hour > end_hour) or (start_hour == end_hour and start_minute > end_minute):
        raise ValidationError("Время окончания не может быть раньше времени начала.")

STATUS_CHOICES = [
    ('working', 'Работает'),
    ('on_leave', 'В отпуске'),
    ('fired', 'Уволен'),
]

class Worker(models.Model):
    fullName = models.CharField(max_length=256, verbose_name='ФИО рабочего')
    dateBirth = models.DateField(verbose_name='Дата рождения')
    workshop = models.ForeignKey(
        'Workshop',
        verbose_name='Цех',
        related_name='workers',
        on_delete=models.CASCADE
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='working',
        verbose_name='Статус'
    )
    workingHours = models.CharField(
        max_length=11,
        verbose_name='Рабочие часы',
        validators=[validate_time_range]
    )

    class Meta:
        verbose_name = 'работник'
        verbose_name_plural = 'Работники'

    def __str__(self):
        return self.fullName

class Workshop(models.Model):
    name = models.CharField(max_length=256, verbose_name='Название места')
    supervisor = models.OneToOneField(
        Worker,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='workshop_supervised',
        verbose_name='Начальник цеха')
    description = models.TextField(verbose_name='Описание')
    numberWorkers = models.IntegerField(default=0, verbose_name='Количество работников')

    class Meta:
        verbose_name = 'цех'
        verbose_name_plural = 'Цехи'

    def __str__(self):
        return self.name

# Сигнал обновления количества работников при добавлении
@receiver(post_save, sender=Worker)
def update_worker_count_on_save(sender, instance, **kwargs):
    workshop = instance.workshop
    workshop.numberWorkers = workshop.workers.count()
    workshop.save()


# Сигнал обновления количества работников при удалении
@receiver(post_delete, sender=Worker)
def update_worker_count_on_delete(sender, instance, **kwargs):
    workshop = instance.workshop
    workshop.numberWorkers = workshop.workers.count()
    workshop.save()

furniture_Factory/order/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy

from order.models import Order


class OrderMixin:
    model = Order
    fields = '__all__'
    success_url = reverse_lazy('order:list_order')

class OrderListView(ListView):
    model = Order
    ordering = 'id'
    paginate_by = 10

class OrderDetailView(DetailView):
    model = Order
    template_name = "order/order_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Если заказы связаны с конкретным цехом, добавляем это
        context['workshop'] = self.object.workshops
        return context

class OrderCreateView(OrderMixin, CreateView):
    pass

class OrderUpdateView(OrderMixin, UpdateView):
    pass

class OrderDeleteView(OrderMixin, DeleteView):
    pass

furniture_Factory/workshop/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.http import Http404

from workshop.models import Workshop, Worker


class WorkerMixin:
    model = Worker
    fields = '__all__'
    success_url = reverse_lazy('workshop:list_worker')

class WorkshopMixin:
    model = Workshop
    fields = ['name', 'supervisor', 'description']
    success_url = reverse_lazy('workshop:list_workshop')

class WorkshopListView(ListView):
    model = Workshop
    ordering = 'id'
    paginate_by = 10

class WorkshopDetailView(DetailView):
    model = Workshop

    def get_object(self, queryset=None):
        obj = get_object_or_404(Workshop, pk=self.kwargs['pk'])
        if not obj:  # Дополнительная проверка, если необходимо
            raise Http404("Цех не найден")
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Получаем работников, связанных с текущим цехом
        context['workers'] = self.object.workers.all()  # Это обращение к related_name 'workers'
        context['orders'] = self.object.orders.all()
        return context

class WorkerListView(ListView):
    model = Worker
    ordering = 'id'
    paginate_by = 10

class WorkshopCreateView(WorkshopMixin, CreateView):
    pass

class WorkshopUpdateView(WorkshopMixin, UpdateView):
    pass

class WorkshopDeleteView(WorkshopMixin, DeleteView):
    pass

class WorkerCreateView(WorkerMixin, CreateView):
    pass

class WorkerUpdateView(WorkerMixin, UpdateView):
    pass

class WorkerDeleteView(WorkerMixin, DeleteView):
    pass

furniture_Factory/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
      {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
</html>

furniture_Factory/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>OOO Мои Цеха</p>
</footer>

furniture_Factory/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'workshop:list_workshop' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Мебельная Фабрика
      </a>
      {% with request.resolver_match.view_name as view_name %}        
        <ul class="nav  nav-pills">
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'workshop:list_workshop' %} active {% endif %}" href="{% url 'workshop:list_workshop' %}">
              Список цехов
            </a>
          </li>
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'workshop:list_worker' %} active {% endif %}" href="{% url 'workshop:list_worker' %}">
              Список рабочих
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'order:list_order' %} active {% endif %}" href="{% url 'order:list_order' %}">
              Список заказов
            </a>
          </li>
        </ul>
      {% endwith %}      
    </div>
  </nav> 
</header>

furniture_Factory/templates/includes/paginator.html
{% load static %}
{% if page_obj.has_other_pages %}
  <nav class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

furniture_Factory/templates/order/order_confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>Удалить заказ</h1>
  <div class="card col-4 m-3">
    <div class="card-header">
       {{ object.orderNumber }}
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_button button_type="submit" content="Удалить" %}
      </form>
    </div>
  </div>
{% endblock content %} 

furniture_Factory/templates/order/order_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">ID заказа: {{ object.id }}</h4>
      <hr>
      {% if object.image %}
        <div class="text-center mb-3">
          <img src="{{ object.image.url }}" class="img-fluid" alt="Изображение заказа" style="max-height: 200px;">
        </div>
      {% endif %}
      <h2 class="card-title">Номер заказа: {{ object.orderNumber }}</h2>
      <p class="card-text"><strong>Дата начала:</strong> {{ object.startDate }}</p>
      <p class="card-text"><strong>Дата окончания:</strong> {{ object.endDate }}</p>
      <p class="card-text"><strong>Статус:</strong> {{ object.get_status_display }}</p>
      <p class="card-text"><strong>Цех:</strong> {{ object.workshops }}</p>
      <p class="card-text"><strong>Описание:</strong> {{ object.description }}</p>
    </div>
  </div>
</div>
{% endblock content %}

furniture_Factory/templates/order/order_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Заказ
{% endblock %}

{% block content %}
  {% with data=form.instance %}
    {% if "/edit/" in request.path %}
      <h2>Редактировать заказ {{ data.orderNumber }}</h2>
    {% elif "/delete/" in request.path %}
      <h2>Удалить заказ {{ data.orderNumber }}</h2>
    {% else %}
      <h2>Добавить новый заказ</h2>
    {% endif %}
    <div class="card col-4">
      <div class="card-header">
        Цех
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% if not "/delete/" in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <p>{{ data.orderNumber }}</p>
            <p>{{ data.startDate }}</p>
            <p>{{ data.endDate }}</p>
            <p>{{ data.status }}</p>
            <p>{{ data.workshops }}</p>
            <p>{{ data.description }}</p>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
    {% if form.is_valid %}
      <h2>Заказ {{ data.orderNumber }} добавлен</h2>
      <div>Id заказа: {{ data.id }}</div>
    {% endif %}
  {% endwith %}
  <hr>
  <div>
    <a href="{% url 'order:list_order' %}">Список всех заказов</a>
  </div>
{% endblock %}

furniture_Factory/templates/order/order_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  <!-- Кнопка для создания нового заказа -->
  <div class="mb-3">
    <a href="{% url 'order:create_order' %}" class="btn btn-primary">
      Создать новый заказ
    </a>
  </div>

  <!-- Список заказов -->
  {% for order in object_list %}
    <div class="card mb-3" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title">Заказ №{{ order.orderNumber }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            Дата начала: {{ order.startDate }} <br>
            Дата окончания: {{ order.endDate }} <br>
            Статус: {{ order.get_status_display }} <br>
            Цех: {{ order.workshops }} <br>
          </small>
        </h6>
        <p class="card-text">{{ order.description|truncatechars:20 }}</p>
        <a href="{% url 'order:edit_order' order.id %}" class="btn btn-warning btn-sm">Редактировать</a>
        <a href="{% url 'order:delete_order' order.id %}" class="btn btn-danger btn-sm">Удалить</a>
        <a href="{% url 'order:detail_order' order.id %}" class="btn btn-info btn-sm">Читать полностью</a>
      </div>
    </div>
  {% empty %}
    <p>Нет заказов.</p>
  {% endfor %}
{% endblock content %}

furniture_Factory/templates/workshop/worker_confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>Удалить рабочего</h1>
  <div class="card col-4 m-3">
    <div class="card-header">
       {{ object.fullName }}
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_button button_type="submit" content="Удалить" %}
      </form>
    </div>
  </div>
{% endblock content %} 

furniture_Factory/templates/workshop/worker_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Цех
{% endblock %}

{% block content %}
  {% with data=form.instance %}
    {% if "/edit/" in request.path %}
      <h2>Редактировать рабочего {{ data.fullName }}</h2>
    {% elif "/delete/" in request.path %}
      <h2>Удалить рабочего {{ data.fullName }}</h2>
    {% else %}
      <h2>Добавить нового рабочего</h2>
    {% endif %}
    <div class="card col-4">
      <div class="card-header">
        Цех
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% if not "/delete/" in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <p>{{ data.fullName }}</p>
            <p>{{ worker.dateBirth }}</p>
            <p>{{ worker.workshop }}</p>
            <p>{{ worker.status }}</p>
            <p>{{ worker.workingHours }}</p>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
    {% if form.is_valid %}
      <h2>Цех {{ data.title }} добавлен</h2>
      <div>Id цеха: {{ data.id }}</div>
    {% endif %}
  {% endwith %}
  <hr>
  <div>
    <a href="{% url 'workshop:list_worker' %}">Список всех работников</a>
  </div>
{% endblock %}

furniture_Factory/templates/workshop/worker_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  <!-- Кнопка для добавления нового рабочего -->
  <div class="mb-3">
    <a href="{% url 'workshop:create_worker' %}" class="btn btn-primary">
      Добавить нового рабочего
    </a>
  </div>

  <!-- Список рабочих -->
  {% for worker in object_list %}
    <div class="card mb-3" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title">{{ worker.fullName }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            ФИО рабочего: {{ worker.fullName }} <br>
            Дата рождения: {{ worker.dateBirth }} <br>
            Цех: {{ worker.workshop }} <br>
            Статус: {{ worker.get_status_display }} <br>
            Время работы: {{ worker.workingHours }} <br>
          </small>
        </h6>
        <a href="{% url 'workshop:edit_worker' worker.id %}" class="btn btn-warning btn-sm">Редактировать</a>
        <a href="{% url 'workshop:delete_worker' worker.id %}" class="btn btn-danger btn-sm">Удалить</a>
      </div>
    </div>
  {% empty %}
    <p>Нет рабочих.</p>
  {% endfor %}
{% endblock content %}

furniture_Factory/templates/workshop/workshop_confirm_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>Удалить цех {{ object.pk }}</h1>
  <div class="card col-4 m-3">
    <div class="card-header">
      {{ workshop.name }}
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        {% bootstrap_button button_type="submit" content="Удалить" %}
      </form>
    </div>
  </div>
{% endblock content %} 

furniture_Factory/templates/workshop/workshop_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">ID цеха: {{ object.id }}</h4>
      <hr>
      {% if object.image %}
        <div class="text-center mb-3">
          <img src="{{ object.image.url }}" class="img-fluid" alt="Изображение цеха" style="max-height: 200px;">
        </div>
      {% endif %}
      <h2 class="card-title">Название цеха: {{ object.name }}</h2>
      <p class="card-text"><strong>Начальник цеха:</strong> {{ object.supervisor }}</p>
      <p class="card-text"><strong>Описание цеха:</strong> {{ object.description }}</p>
      <p class="card-text"><strong>Количество работников:</strong> {{ object.numberWorkers }}</p>
    </div>
  </div>

  <!-- Секция с работниками -->
  <div class="mt-4">
    <h3>Работники цеха:</h3>
    {% if workers %}
      <ul class="list-group">
        {% for worker in workers %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ worker.fullName }}
            <span>
              <a href="{% url 'workshop:edit_worker' worker.id %}" class="btn btn-sm btn-primary">Редактировать</a>
              <a href="{% url 'workshop:delete_worker' worker.id %}" class="btn btn-sm btn-danger">Удалить</a>
            </span>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="text-muted">Нет работников в этом цехе.</p>
    {% endif %}
  </div>

  <!-- Секция с заказами -->
  <div class="mt-4">
    <h3>Заказы, обрабатываемые в этом цеху:</h3>
    {% if orders %}
      <ul class="list-group">
        {% for order in orders %}
          <li class="list-group-item">
            <h5>Заказ #{{ order.orderNumber }}</h5>
            <p><strong>Дата начала:</strong> {{ order.startDate }}</p>
            <p><strong>Дата окончания:</strong> {{ order.endDate }}</p>
            <p><strong>Статус:</strong> {{ order.get_status_display }}</p>
            <p><strong>Описание:</strong> {{ order.description|truncatechars:50 }}</p>
            <a href="{% url 'order:detail_order' order.id %}" class="btn btn-sm btn-info">Подробнее</a>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <p class="text-muted">Нет заказов в этом цеху.</p>
    {% endif %}
  </div>
</div>
{% endblock content %}

furniture_Factory/templates/workshop/workshop_form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
  Цех
{% endblock %}

{% block content %}
  {% with data=form.instance %}
    {% if "/edit/" in request.path %}
      <h2>Редактировать цех {{ data.name }}</h2>
    {% elif "/delete/" in request.path %}
      <h2>Удалить цех {{ data.pk }}</h2>
    {% else %}
      <h2>Добавить новый цех</h2>
    {% endif %}
    <div class="card col-4">
      <div class="card-header">
        Цех
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% if not "/delete/" in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <p>{{ data.name }}</p>
            <p>{{ data.supervisor }}</p>
            <p>{{ data.description }}</p>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
    {% if form.is_valid %}
      <h2>Цех {{ data.name }} добавлен</h2>
      <div>Id цеха: {{ data.id }}</div>
    {% endif %}
  {% endwith %}
  <hr>
  <div>
    <a href="{% url 'workshop:list_workshop' %}">Список всех цехов</a>
  </div>
{% endblock %}

furniture_Factory/templates/workshop/workshop_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  <!-- Кнопка для добавления нового цеха -->
  <div class="mb-3">
    <a href="{% url 'workshop:create_workshop' %}" class="btn btn-primary">
      Добавить новый цех
    </a>
  </div>

  <!-- Список цехов -->
  {% for workshop in object_list %}
    <div class="card mb-3" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title">{{ workshop.name }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            Название цеха: {{ workshop.name }} <br>
            Начальник цеха: {{ workshop.supervisor }} <br>
            Количество работников: {{ workshop.numberWorkers }} <br>
          </small>
        </h6>
        <p class="card-text">{{ workshop.description|truncatechars:20 }}</p>
        <a href="{% url 'workshop:edit_workshop' workshop.id %}" class="btn btn-warning btn-sm">Редактировать</a>
        <a href="{% url 'workshop:delete_workshop' workshop.id %}" class="btn btn-danger btn-sm">Удалить</a>
        <a href="{% url 'workshop:detail_workshop' workshop.id %}" class="btn btn-info btn-sm">Читать полностью</a>
      </div>
    </div>
  {% empty %}
    <p>Нет цехов.</p>
  {% endfor %}
{% endblock content %}

templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>    
</footer>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>
      {% with request.resolver_match.view_name as view_name %}        
        <ul class="nav  nav-pills">
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'blog:index' %} active {% endif %}" href="{% url 'blog:index' %}">
              Лента записей
            </a>
          </li>
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'pages:about' %} active {% endif %}" href="{% url 'pages:about' %}">
              О проекте
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:rules' %} active {% endif %}" href="{% url 'pages:rules' %}">
              Наши правила
            </a>
          </li>
        </ul>
      {% endwith %}      
    </div>
  </nav> 
</header>